name: DevOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: bilaalahmed/devops-cloud-project

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t devops-web:test .

      - name: Test container
        run: |
          docker run -d --name devops-test -p 8080:80 devops-web:test
          sleep 5
          curl --fail http://localhost:8080
          docker stop devops-test
          docker rm devops-test

  build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ github.sha }} \
            -t $IMAGE_NAME:latest \
            .

      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Logging in to Docker Hub..."
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            echo "Pulling new Docker image..."
            docker pull bilaalahmed/devops-cloud-project:${{ github.sha }}

            echo "Stopping old container..."
            docker stop devops-web || true

            echo "Removing old container..."
            docker rm devops-web || true

            echo "Starting new container..."
            docker run -d \
              --name devops-web \
              --restart unless-stopped \
              -p 80:80 \
              bilaalahmed/devops-cloud-project:${{ github.sha }}

            echo "Checking container..."
            docker ps

            echo "Testing application..."
            sleep 5
            curl --fail http://localhost

            echo "Deployment successful!"
