name: DevOps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t devops-web:test .

      - name: Test container
        run: |
          docker run -d --name devops-test -p 8080:80 devops-web:test
          sleep 5
          curl --fail http://localhost:8080
          docker stop devops-test
          docker rm devops-test
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH connection to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Connected to EC2 successfully"
            hostname
            whoami
            docker --version
